# Docker context should be "<repo-root>"

FROM node:8.9.4
LABEL maintainer="OpusCapita"

RUN mkdir /demo

COPY ./ /demo

WORKDIR /demo

RUN npm i && \
  cd ./packages/examples/complete-demo && \
  npm run demo:build

WORKDIR /demo/packages/examples/complete-demo

CMD ["npm", "run", "demo:start"]

EXPOSE 3020